/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package bell;

/**
 *
 * @author HPro1
 */
public class TipCalculator extends javax.swing.JFrame {

    //variables
    
    /**
     * Creates new form TipCalculator
     */
    public TipCalculator() {
        initComponents();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        currentBillTextField = new javax.swing.JTextField();
        tipSelectLabel = new javax.swing.JLabel();
        tipSlider = new javax.swing.JSlider();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        tipAmountLabel = new javax.swing.JLabel();
        totalBillLabel = new javax.swing.JLabel();
        resetButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Current Bill:");
        jLabel1.setToolTipText("");

        currentBillTextField.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        currentBillTextField.setText("$0.00");
        currentBillTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                currentBillTextFieldActionPerformed(evt);
            }
        });

        tipSelectLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        tipSelectLabel.setText("Slide to Select Tip: 20%");

        tipSlider.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                tipSliderStateChanged(evt);
            }
        });

        jLabel3.setText("Tip Amount:");

        jLabel4.setText("Total Bill:");

        tipAmountLabel.setText("$0.00");

        totalBillLabel.setText("$0.00");

        resetButton.setText("Reset");
        resetButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel3))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(totalBillLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 153, Short.MAX_VALUE)
                            .addComponent(tipAmountLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(tipSlider, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(tipSelectLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel1)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(currentBillTextField))))))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(95, 95, 95)
                .addComponent(resetButton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(currentBillTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(tipSelectLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tipSlider, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(tipAmountLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(totalBillLabel))
                .addGap(18, 18, 18)
                .addComponent(resetButton)
                .addContainerGap(20, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tipSliderStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_tipSliderStateChanged
    int sliderValue = tipSlider.getValue();
    tipSelectLabel.setText("Slide to Select Tip: " + sliderValue + "%");
    
    updateTotal();
    }//GEN-LAST:event_tipSliderStateChanged

    private void currentBillTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_currentBillTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_currentBillTextFieldActionPerformed

    private void resetButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetButtonActionPerformed
currentBillTextField.setText("$0.00");
tipSlider.setValue(20);
totalBillLabel.setText("$0.00");
tipAmountLabel.setText("$0.00");
    }//GEN-LAST:event_resetButtonActionPerformed
// methods
    private void updateTotal(){
        if (!currentBillTextField.getText().equals("$0.00")) {
       String bill = currentBillTextField.getText();
       double numericBill = doubleFromCash(bill);
       double sliderValue = tipSlider.getValue();
       double tip = (sliderValue / 100.0) * numericBill;
       double totalBill = numericBill + tip;
       tipAmountLabel.setText(convertToCash(tip));
       totalBillLabel.setText(convertToCash(totalBill));
        }
    }
 private String convertToCash (double amount) {
   String cash = String.format("$%,.2f",amount);
   return cash;
 }
    private double doubleFromCash(String cash) {
  cash =  cash.replace("$", "");
  cash =  cash.replace(",", "");
  if (isNumeric(cash)){ 
        return Double.parseDouble(cash);
    } else {
        return 0.0;
    }
    }
    
    private boolean isNumeric (String text) {
        return isDouble(text) || isInteger(text);
    }
    
   private boolean isDouble (String text) {
       double newDouble = 0.0;
       try {
           newDouble = Double.valueOf(text);
       } catch (NumberFormatException error) {
           return false;
       }
       return true;
   }
    private boolean isInteger(String text) {
        int newInteger = 0;
        try { 
            newInteger = Integer.valueOf(text);
        } catch (NumberFormatException error) {
    }
                return false;
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TipCalculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TipCalculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TipCalculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TipCalculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TipCalculator().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField currentBillTextField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JButton resetButton;
    private javax.swing.JLabel tipAmountLabel;
    private javax.swing.JLabel tipSelectLabel;
    private javax.swing.JSlider tipSlider;
    private javax.swing.JLabel totalBillLabel;
    // End of variables declaration//GEN-END:variables


}
